{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "context-skills.serviceAccountName" . }}
  labels:
    {{- include "context-skills.labels" . | nindent 4 }}
{{- end }}
