apiVersion: v1
kind: Service
metadata:
  name: {{ include "context-skills.fullname" . }}-api
  labels:
    {{- include "context-skills.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "context-skills.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
